//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edge.Services.Google.Adwords.ReportService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public partial class ApiException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private ApiError[] errorsField;
        
        private bool internalField;
        
        private string messageField;
        
        private string triggerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errors", IsNullable=true, Order=1)]
        public ApiError[] errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool @internal {
            get {
                return this.internalField;
            }
            set {
                this.internalField = value;
                this.RaisePropertyChanged("internal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string trigger {
            get {
                return this.triggerField;
            }
            set {
                this.triggerField = value;
                this.RaisePropertyChanged("trigger");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public partial class ApiError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string detailField;
        
        private string fieldField;
        
        private int indexField;
        
        private bool isExemptableField;
        
        private int textIndexField;
        
        private bool textIndexFieldSpecified;
        
        private int textLengthField;
        
        private bool textLengthFieldSpecified;
        
        private string triggerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("detail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
                this.RaisePropertyChanged("index");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool isExemptable {
            get {
                return this.isExemptableField;
            }
            set {
                this.isExemptableField = value;
                this.RaisePropertyChanged("isExemptable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int textIndex {
            get {
                return this.textIndexField;
            }
            set {
                this.textIndexField = value;
                this.RaisePropertyChanged("textIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool textIndexSpecified {
            get {
                return this.textIndexFieldSpecified;
            }
            set {
                this.textIndexFieldSpecified = value;
                this.RaisePropertyChanged("textIndexSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int textLength {
            get {
                return this.textLengthField;
            }
            set {
                this.textLengthField = value;
                this.RaisePropertyChanged("textLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool textLengthSpecified {
            get {
                return this.textLengthFieldSpecified;
            }
            set {
                this.textLengthFieldSpecified = value;
                this.RaisePropertyChanged("textLengthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string trigger {
            get {
                return this.triggerField;
            }
            set {
                this.triggerField = value;
                this.RaisePropertyChanged("trigger");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://adwords.google.com/api/adwords/v13", ConfigurationName="ReportService.ReportInterface")]
    public interface ReportInterface {
        
        // CODEGEN: Generating message contract since message deleteReportRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Edge.Services.Google.Adwords.ReportService.ApiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Edge.Services.Google.Adwords.ReportService.deleteReportResponse deleteReport(Edge.Services.Google.Adwords.ReportService.deleteReportRequest request);
        
        // CODEGEN: Generating message contract since message getAllJobsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Edge.Services.Google.Adwords.ReportService.ApiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Edge.Services.Google.Adwords.ReportService.getAllJobsResponse getAllJobs(Edge.Services.Google.Adwords.ReportService.getAllJobsRequest request);
        
        // CODEGEN: Generating message contract since message getGzipReportDownloadUrlRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Edge.Services.Google.Adwords.ReportService.ApiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Edge.Services.Google.Adwords.ReportService.getGzipReportDownloadUrlResponse getGzipReportDownloadUrl(Edge.Services.Google.Adwords.ReportService.getGzipReportDownloadUrlRequest request);
        
        // CODEGEN: Generating message contract since message getReportDownloadUrlRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Edge.Services.Google.Adwords.ReportService.ApiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Edge.Services.Google.Adwords.ReportService.getReportDownloadUrlResponse getReportDownloadUrl(Edge.Services.Google.Adwords.ReportService.getReportDownloadUrlRequest request);
        
        // CODEGEN: Generating message contract since message getReportJobStatusRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Edge.Services.Google.Adwords.ReportService.ApiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Edge.Services.Google.Adwords.ReportService.getReportJobStatusResponse getReportJobStatus(Edge.Services.Google.Adwords.ReportService.getReportJobStatusRequest request);
        
        // CODEGEN: Generating message contract since message scheduleReportJobRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Edge.Services.Google.Adwords.ReportService.ApiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Edge.Services.Google.Adwords.ReportService.scheduleReportJobResponse scheduleReportJob(Edge.Services.Google.Adwords.ReportService.scheduleReportJobRequest request);
        
        // CODEGEN: Generating message contract since message validateReportJobRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Edge.Services.Google.Adwords.ReportService.ApiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Edge.Services.Google.Adwords.ReportService.validateReportJobResponse validateReportJob(Edge.Services.Google.Adwords.ReportService.validateReportJobRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteReport", WrapperNamespace="https://adwords.google.com/api/adwords/v13", IsWrapped=true)]
    public partial class deleteReportRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string useragent;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string email;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string clientEmail;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string clientCustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string developerToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string applicationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/v13", Order=0)]
        public long reportJobId;
        
        public deleteReportRequest() {
        }
        
        public deleteReportRequest(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken, long reportJobId) {
            this.useragent = useragent;
            this.password = password;
            this.email = email;
            this.clientEmail = clientEmail;
            this.clientCustomerId = clientCustomerId;
            this.developerToken = developerToken;
            this.applicationToken = applicationToken;
            this.reportJobId = reportJobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteReportResponse", WrapperNamespace="https://adwords.google.com/api/adwords/v13", IsWrapped=true)]
    public partial class deleteReportResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long responseTime;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long operations;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long units;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string requestId;
        
        public deleteReportResponse() {
        }
        
        public deleteReportResponse(long responseTime, long operations, long units, string requestId) {
            this.responseTime = responseTime;
            this.operations = operations;
            this.units = units;
            this.requestId = requestId;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DefinedReportJob))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public abstract partial class ReportJob : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] clientEmailsField;
        
        private bool crossClientField;
        
        private bool crossClientFieldSpecified;
        
        private System.DateTime endDayField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private System.DateTime startDayField;
        
        private ReportJobStatus statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clientEmails", Order=0)]
        public string[] clientEmails {
            get {
                return this.clientEmailsField;
            }
            set {
                this.clientEmailsField = value;
                this.RaisePropertyChanged("clientEmails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool crossClient {
            get {
                return this.crossClientField;
            }
            set {
                this.crossClientField = value;
                this.RaisePropertyChanged("crossClient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool crossClientSpecified {
            get {
                return this.crossClientFieldSpecified;
            }
            set {
                this.crossClientFieldSpecified = value;
                this.RaisePropertyChanged("crossClientSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime endDay {
            get {
                return this.endDayField;
            }
            set {
                this.endDayField = value;
                this.RaisePropertyChanged("endDay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime startDay {
            get {
                return this.startDayField;
            }
            set {
                this.startDayField = value;
                this.RaisePropertyChanged("startDay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public ReportJobStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public enum ReportJobStatus {
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        InProgress,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public partial class DefinedReportJob : ReportJob {
        
        private AdGroupStatus[] adGroupStatusesField;
        
        private long[] adGroupsField;
        
        private AdWordsType adWordsTypeField;
        
        private bool adWordsTypeFieldSpecified;
        
        private string[] aggregationTypesField;
        
        private CampaignStatus[] campaignStatusesField;
        
        private int[] campaignsField;
        
        private bool includeZeroImpressionField;
        
        private bool includeZeroImpressionFieldSpecified;
        
        private KeywordStatus[] keywordStatusesField;
        
        private KeywordType keywordTypeField;
        
        private bool keywordTypeFieldSpecified;
        
        private string[] keywordsField;
        
        private string[] selectedColumnsField;
        
        private string selectedReportTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("adGroupStatuses", Order=0)]
        public AdGroupStatus[] adGroupStatuses {
            get {
                return this.adGroupStatusesField;
            }
            set {
                this.adGroupStatusesField = value;
                this.RaisePropertyChanged("adGroupStatuses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("adGroups", Order=1)]
        public long[] adGroups {
            get {
                return this.adGroupsField;
            }
            set {
                this.adGroupsField = value;
                this.RaisePropertyChanged("adGroups");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AdWordsType adWordsType {
            get {
                return this.adWordsTypeField;
            }
            set {
                this.adWordsTypeField = value;
                this.RaisePropertyChanged("adWordsType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adWordsTypeSpecified {
            get {
                return this.adWordsTypeFieldSpecified;
            }
            set {
                this.adWordsTypeFieldSpecified = value;
                this.RaisePropertyChanged("adWordsTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aggregationTypes", Order=3)]
        public string[] aggregationTypes {
            get {
                return this.aggregationTypesField;
            }
            set {
                this.aggregationTypesField = value;
                this.RaisePropertyChanged("aggregationTypes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("campaignStatuses", Order=4)]
        public CampaignStatus[] campaignStatuses {
            get {
                return this.campaignStatusesField;
            }
            set {
                this.campaignStatusesField = value;
                this.RaisePropertyChanged("campaignStatuses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("campaigns", Order=5)]
        public int[] campaigns {
            get {
                return this.campaignsField;
            }
            set {
                this.campaignsField = value;
                this.RaisePropertyChanged("campaigns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool includeZeroImpression {
            get {
                return this.includeZeroImpressionField;
            }
            set {
                this.includeZeroImpressionField = value;
                this.RaisePropertyChanged("includeZeroImpression");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool includeZeroImpressionSpecified {
            get {
                return this.includeZeroImpressionFieldSpecified;
            }
            set {
                this.includeZeroImpressionFieldSpecified = value;
                this.RaisePropertyChanged("includeZeroImpressionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keywordStatuses", Order=7)]
        public KeywordStatus[] keywordStatuses {
            get {
                return this.keywordStatusesField;
            }
            set {
                this.keywordStatusesField = value;
                this.RaisePropertyChanged("keywordStatuses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public KeywordType keywordType {
            get {
                return this.keywordTypeField;
            }
            set {
                this.keywordTypeField = value;
                this.RaisePropertyChanged("keywordType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool keywordTypeSpecified {
            get {
                return this.keywordTypeFieldSpecified;
            }
            set {
                this.keywordTypeFieldSpecified = value;
                this.RaisePropertyChanged("keywordTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keywords", Order=9)]
        public string[] keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
                this.RaisePropertyChanged("keywords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("selectedColumns", Order=10)]
        public string[] selectedColumns {
            get {
                return this.selectedColumnsField;
            }
            set {
                this.selectedColumnsField = value;
                this.RaisePropertyChanged("selectedColumns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string selectedReportType {
            get {
                return this.selectedReportTypeField;
            }
            set {
                this.selectedReportTypeField = value;
                this.RaisePropertyChanged("selectedReportType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public enum AdGroupStatus {
        
        /// <remarks/>
        Enabled,
        
        /// <remarks/>
        Paused,
        
        /// <remarks/>
        Deleted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public enum AdWordsType {
        
        /// <remarks/>
        SearchOnly,
        
        /// <remarks/>
        ContentOnly,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public enum CampaignStatus {
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Ended,
        
        /// <remarks/>
        Paused,
        
        /// <remarks/>
        Deleted,
        
        /// <remarks/>
        Suspended,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public enum KeywordStatus {
        
        /// <remarks/>
        Disapproved,
        
        /// <remarks/>
        Deleted,
        
        /// <remarks/>
        Paused,
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        InActive,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public enum KeywordType {
        
        /// <remarks/>
        Broad,
        
        /// <remarks/>
        Phrase,
        
        /// <remarks/>
        Exact,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllJobs", WrapperNamespace="https://adwords.google.com/api/adwords/v13", IsWrapped=true)]
    public partial class getAllJobsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string useragent;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string email;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string clientEmail;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string clientCustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string developerToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string applicationToken;
        
        public getAllJobsRequest() {
        }
        
        public getAllJobsRequest(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken) {
            this.useragent = useragent;
            this.password = password;
            this.email = email;
            this.clientEmail = clientEmail;
            this.clientCustomerId = clientCustomerId;
            this.developerToken = developerToken;
            this.applicationToken = applicationToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllJobsResponse", WrapperNamespace="https://adwords.google.com/api/adwords/v13", IsWrapped=true)]
    public partial class getAllJobsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long responseTime;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long operations;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long units;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string requestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/v13", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getAllJobsReturn")]
        public ReportJob[] getAllJobsReturn;
        
        public getAllJobsResponse() {
        }
        
        public getAllJobsResponse(long responseTime, long operations, long units, string requestId, ReportJob[] getAllJobsReturn) {
            this.responseTime = responseTime;
            this.operations = operations;
            this.units = units;
            this.requestId = requestId;
            this.getAllJobsReturn = getAllJobsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGzipReportDownloadUrl", WrapperNamespace="https://adwords.google.com/api/adwords/v13", IsWrapped=true)]
    public partial class getGzipReportDownloadUrlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string useragent;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string email;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string clientEmail;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string clientCustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string developerToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string applicationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/v13", Order=0)]
        public long reportJobId;
        
        public getGzipReportDownloadUrlRequest() {
        }
        
        public getGzipReportDownloadUrlRequest(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken, long reportJobId) {
            this.useragent = useragent;
            this.password = password;
            this.email = email;
            this.clientEmail = clientEmail;
            this.clientCustomerId = clientCustomerId;
            this.developerToken = developerToken;
            this.applicationToken = applicationToken;
            this.reportJobId = reportJobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGzipReportDownloadUrlResponse", WrapperNamespace="https://adwords.google.com/api/adwords/v13", IsWrapped=true)]
    public partial class getGzipReportDownloadUrlResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long responseTime;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long operations;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long units;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string requestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/v13", Order=0)]
        public string getGzipReportDownloadUrlReturn;
        
        public getGzipReportDownloadUrlResponse() {
        }
        
        public getGzipReportDownloadUrlResponse(long responseTime, long operations, long units, string requestId, string getGzipReportDownloadUrlReturn) {
            this.responseTime = responseTime;
            this.operations = operations;
            this.units = units;
            this.requestId = requestId;
            this.getGzipReportDownloadUrlReturn = getGzipReportDownloadUrlReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReportDownloadUrl", WrapperNamespace="https://adwords.google.com/api/adwords/v13", IsWrapped=true)]
    public partial class getReportDownloadUrlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string useragent;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string email;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string clientEmail;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string clientCustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string developerToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string applicationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/v13", Order=0)]
        public long reportJobId;
        
        public getReportDownloadUrlRequest() {
        }
        
        public getReportDownloadUrlRequest(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken, long reportJobId) {
            this.useragent = useragent;
            this.password = password;
            this.email = email;
            this.clientEmail = clientEmail;
            this.clientCustomerId = clientCustomerId;
            this.developerToken = developerToken;
            this.applicationToken = applicationToken;
            this.reportJobId = reportJobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReportDownloadUrlResponse", WrapperNamespace="https://adwords.google.com/api/adwords/v13", IsWrapped=true)]
    public partial class getReportDownloadUrlResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long responseTime;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long operations;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long units;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string requestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/v13", Order=0)]
        public string getReportDownloadUrlReturn;
        
        public getReportDownloadUrlResponse() {
        }
        
        public getReportDownloadUrlResponse(long responseTime, long operations, long units, string requestId, string getReportDownloadUrlReturn) {
            this.responseTime = responseTime;
            this.operations = operations;
            this.units = units;
            this.requestId = requestId;
            this.getReportDownloadUrlReturn = getReportDownloadUrlReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReportJobStatus", WrapperNamespace="https://adwords.google.com/api/adwords/v13", IsWrapped=true)]
    public partial class getReportJobStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string useragent;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string email;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string clientEmail;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string clientCustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string developerToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string applicationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/v13", Order=0)]
        public long reportJobId;
        
        public getReportJobStatusRequest() {
        }
        
        public getReportJobStatusRequest(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken, long reportJobId) {
            this.useragent = useragent;
            this.password = password;
            this.email = email;
            this.clientEmail = clientEmail;
            this.clientCustomerId = clientCustomerId;
            this.developerToken = developerToken;
            this.applicationToken = applicationToken;
            this.reportJobId = reportJobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReportJobStatusResponse", WrapperNamespace="https://adwords.google.com/api/adwords/v13", IsWrapped=true)]
    public partial class getReportJobStatusResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long responseTime;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long operations;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long units;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string requestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/v13", Order=0)]
        public Edge.Services.Google.Adwords.ReportService.ReportJobStatus getReportJobStatusReturn;
        
        public getReportJobStatusResponse() {
        }
        
        public getReportJobStatusResponse(long responseTime, long operations, long units, string requestId, Edge.Services.Google.Adwords.ReportService.ReportJobStatus getReportJobStatusReturn) {
            this.responseTime = responseTime;
            this.operations = operations;
            this.units = units;
            this.requestId = requestId;
            this.getReportJobStatusReturn = getReportJobStatusReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="scheduleReportJob", WrapperNamespace="https://adwords.google.com/api/adwords/v13", IsWrapped=true)]
    public partial class scheduleReportJobRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string useragent;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string email;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string clientEmail;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string clientCustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string developerToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string applicationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/v13", Order=0)]
        public Edge.Services.Google.Adwords.ReportService.ReportJob job;
        
        public scheduleReportJobRequest() {
        }
        
        public scheduleReportJobRequest(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken, Edge.Services.Google.Adwords.ReportService.ReportJob job) {
            this.useragent = useragent;
            this.password = password;
            this.email = email;
            this.clientEmail = clientEmail;
            this.clientCustomerId = clientCustomerId;
            this.developerToken = developerToken;
            this.applicationToken = applicationToken;
            this.job = job;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="scheduleReportJobResponse", WrapperNamespace="https://adwords.google.com/api/adwords/v13", IsWrapped=true)]
    public partial class scheduleReportJobResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long responseTime;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long operations;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long units;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string requestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/v13", Order=0)]
        public long scheduleReportJobReturn;
        
        public scheduleReportJobResponse() {
        }
        
        public scheduleReportJobResponse(long responseTime, long operations, long units, string requestId, long scheduleReportJobReturn) {
            this.responseTime = responseTime;
            this.operations = operations;
            this.units = units;
            this.requestId = requestId;
            this.scheduleReportJobReturn = scheduleReportJobReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateReportJob", WrapperNamespace="https://adwords.google.com/api/adwords/v13", IsWrapped=true)]
    public partial class validateReportJobRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string useragent;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string email;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string clientEmail;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string clientCustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string developerToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string applicationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/v13", Order=0)]
        public Edge.Services.Google.Adwords.ReportService.ReportJob job;
        
        public validateReportJobRequest() {
        }
        
        public validateReportJobRequest(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken, Edge.Services.Google.Adwords.ReportService.ReportJob job) {
            this.useragent = useragent;
            this.password = password;
            this.email = email;
            this.clientEmail = clientEmail;
            this.clientCustomerId = clientCustomerId;
            this.developerToken = developerToken;
            this.applicationToken = applicationToken;
            this.job = job;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateReportJobResponse", WrapperNamespace="https://adwords.google.com/api/adwords/v13", IsWrapped=true)]
    public partial class validateReportJobResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long responseTime;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long operations;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public long units;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
        public string requestId;
        
        public validateReportJobResponse() {
        }
        
        public validateReportJobResponse(long responseTime, long operations, long units, string requestId) {
            this.responseTime = responseTime;
            this.operations = operations;
            this.units = units;
            this.requestId = requestId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportInterfaceChannel : Edge.Services.Google.Adwords.ReportService.ReportInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportInterfaceClient : System.ServiceModel.ClientBase<Edge.Services.Google.Adwords.ReportService.ReportInterface>, Edge.Services.Google.Adwords.ReportService.ReportInterface {
        
        public ReportInterfaceClient() {
        }
        
        public ReportInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Edge.Services.Google.Adwords.ReportService.deleteReportResponse Edge.Services.Google.Adwords.ReportService.ReportInterface.deleteReport(Edge.Services.Google.Adwords.ReportService.deleteReportRequest request) {
            return base.Channel.deleteReport(request);
        }
        
        public long deleteReport(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken, long reportJobId, out long operations, out long units, out string requestId) {
            Edge.Services.Google.Adwords.ReportService.deleteReportRequest inValue = new Edge.Services.Google.Adwords.ReportService.deleteReportRequest();
            inValue.useragent = useragent;
            inValue.password = password;
            inValue.email = email;
            inValue.clientEmail = clientEmail;
            inValue.clientCustomerId = clientCustomerId;
            inValue.developerToken = developerToken;
            inValue.applicationToken = applicationToken;
            inValue.reportJobId = reportJobId;
            Edge.Services.Google.Adwords.ReportService.deleteReportResponse retVal = ((Edge.Services.Google.Adwords.ReportService.ReportInterface)(this)).deleteReport(inValue);
            operations = retVal.operations;
            units = retVal.units;
            requestId = retVal.requestId;
            return retVal.responseTime;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Edge.Services.Google.Adwords.ReportService.getAllJobsResponse Edge.Services.Google.Adwords.ReportService.ReportInterface.getAllJobs(Edge.Services.Google.Adwords.ReportService.getAllJobsRequest request) {
            return base.Channel.getAllJobs(request);
        }
        
        public long getAllJobs(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken, out long operations, out long units, out string requestId, out ReportJob[] getAllJobsReturn) {
            Edge.Services.Google.Adwords.ReportService.getAllJobsRequest inValue = new Edge.Services.Google.Adwords.ReportService.getAllJobsRequest();
            inValue.useragent = useragent;
            inValue.password = password;
            inValue.email = email;
            inValue.clientEmail = clientEmail;
            inValue.clientCustomerId = clientCustomerId;
            inValue.developerToken = developerToken;
            inValue.applicationToken = applicationToken;
            Edge.Services.Google.Adwords.ReportService.getAllJobsResponse retVal = ((Edge.Services.Google.Adwords.ReportService.ReportInterface)(this)).getAllJobs(inValue);
            operations = retVal.operations;
            units = retVal.units;
            requestId = retVal.requestId;
            getAllJobsReturn = retVal.getAllJobsReturn;
            return retVal.responseTime;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Edge.Services.Google.Adwords.ReportService.getGzipReportDownloadUrlResponse Edge.Services.Google.Adwords.ReportService.ReportInterface.getGzipReportDownloadUrl(Edge.Services.Google.Adwords.ReportService.getGzipReportDownloadUrlRequest request) {
            return base.Channel.getGzipReportDownloadUrl(request);
        }
        
        public long getGzipReportDownloadUrl(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken, long reportJobId, out long operations, out long units, out string requestId, out string getGzipReportDownloadUrlReturn) {
            Edge.Services.Google.Adwords.ReportService.getGzipReportDownloadUrlRequest inValue = new Edge.Services.Google.Adwords.ReportService.getGzipReportDownloadUrlRequest();
            inValue.useragent = useragent;
            inValue.password = password;
            inValue.email = email;
            inValue.clientEmail = clientEmail;
            inValue.clientCustomerId = clientCustomerId;
            inValue.developerToken = developerToken;
            inValue.applicationToken = applicationToken;
            inValue.reportJobId = reportJobId;
            Edge.Services.Google.Adwords.ReportService.getGzipReportDownloadUrlResponse retVal = ((Edge.Services.Google.Adwords.ReportService.ReportInterface)(this)).getGzipReportDownloadUrl(inValue);
            operations = retVal.operations;
            units = retVal.units;
            requestId = retVal.requestId;
            getGzipReportDownloadUrlReturn = retVal.getGzipReportDownloadUrlReturn;
            return retVal.responseTime;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Edge.Services.Google.Adwords.ReportService.getReportDownloadUrlResponse Edge.Services.Google.Adwords.ReportService.ReportInterface.getReportDownloadUrl(Edge.Services.Google.Adwords.ReportService.getReportDownloadUrlRequest request) {
            return base.Channel.getReportDownloadUrl(request);
        }
        
        public long getReportDownloadUrl(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken, long reportJobId, out long operations, out long units, out string requestId, out string getReportDownloadUrlReturn) {
            Edge.Services.Google.Adwords.ReportService.getReportDownloadUrlRequest inValue = new Edge.Services.Google.Adwords.ReportService.getReportDownloadUrlRequest();
            inValue.useragent = useragent;
            inValue.password = password;
            inValue.email = email;
            inValue.clientEmail = clientEmail;
            inValue.clientCustomerId = clientCustomerId;
            inValue.developerToken = developerToken;
            inValue.applicationToken = applicationToken;
            inValue.reportJobId = reportJobId;
            Edge.Services.Google.Adwords.ReportService.getReportDownloadUrlResponse retVal = ((Edge.Services.Google.Adwords.ReportService.ReportInterface)(this)).getReportDownloadUrl(inValue);
            operations = retVal.operations;
            units = retVal.units;
            requestId = retVal.requestId;
            getReportDownloadUrlReturn = retVal.getReportDownloadUrlReturn;
            return retVal.responseTime;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Edge.Services.Google.Adwords.ReportService.getReportJobStatusResponse Edge.Services.Google.Adwords.ReportService.ReportInterface.getReportJobStatus(Edge.Services.Google.Adwords.ReportService.getReportJobStatusRequest request) {
            return base.Channel.getReportJobStatus(request);
        }
        
        public long getReportJobStatus(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken, long reportJobId, out long operations, out long units, out string requestId, out Edge.Services.Google.Adwords.ReportService.ReportJobStatus getReportJobStatusReturn) {
            Edge.Services.Google.Adwords.ReportService.getReportJobStatusRequest inValue = new Edge.Services.Google.Adwords.ReportService.getReportJobStatusRequest();
            inValue.useragent = useragent;
            inValue.password = password;
            inValue.email = email;
            inValue.clientEmail = clientEmail;
            inValue.clientCustomerId = clientCustomerId;
            inValue.developerToken = developerToken;
            inValue.applicationToken = applicationToken;
            inValue.reportJobId = reportJobId;
            Edge.Services.Google.Adwords.ReportService.getReportJobStatusResponse retVal = ((Edge.Services.Google.Adwords.ReportService.ReportInterface)(this)).getReportJobStatus(inValue);
            operations = retVal.operations;
            units = retVal.units;
            requestId = retVal.requestId;
            getReportJobStatusReturn = retVal.getReportJobStatusReturn;
            return retVal.responseTime;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Edge.Services.Google.Adwords.ReportService.scheduleReportJobResponse Edge.Services.Google.Adwords.ReportService.ReportInterface.scheduleReportJob(Edge.Services.Google.Adwords.ReportService.scheduleReportJobRequest request) {
            return base.Channel.scheduleReportJob(request);
        }
        
        public long scheduleReportJob(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken, Edge.Services.Google.Adwords.ReportService.ReportJob job, out long operations, out long units, out string requestId, out long scheduleReportJobReturn) {
            Edge.Services.Google.Adwords.ReportService.scheduleReportJobRequest inValue = new Edge.Services.Google.Adwords.ReportService.scheduleReportJobRequest();
            inValue.useragent = useragent;
            inValue.password = password;
            inValue.email = email;
            inValue.clientEmail = clientEmail;
            inValue.clientCustomerId = clientCustomerId;
            inValue.developerToken = developerToken;
            inValue.applicationToken = applicationToken;
            inValue.job = job;
            Edge.Services.Google.Adwords.ReportService.scheduleReportJobResponse retVal = ((Edge.Services.Google.Adwords.ReportService.ReportInterface)(this)).scheduleReportJob(inValue);
            operations = retVal.operations;
            units = retVal.units;
            requestId = retVal.requestId;
            scheduleReportJobReturn = retVal.scheduleReportJobReturn;
            return retVal.responseTime;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Edge.Services.Google.Adwords.ReportService.validateReportJobResponse Edge.Services.Google.Adwords.ReportService.ReportInterface.validateReportJob(Edge.Services.Google.Adwords.ReportService.validateReportJobRequest request) {
            return base.Channel.validateReportJob(request);
        }
        
        public long validateReportJob(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken, Edge.Services.Google.Adwords.ReportService.ReportJob job, out long operations, out long units, out string requestId) {
            Edge.Services.Google.Adwords.ReportService.validateReportJobRequest inValue = new Edge.Services.Google.Adwords.ReportService.validateReportJobRequest();
            inValue.useragent = useragent;
            inValue.password = password;
            inValue.email = email;
            inValue.clientEmail = clientEmail;
            inValue.clientCustomerId = clientCustomerId;
            inValue.developerToken = developerToken;
            inValue.applicationToken = applicationToken;
            inValue.job = job;
            Edge.Services.Google.Adwords.ReportService.validateReportJobResponse retVal = ((Edge.Services.Google.Adwords.ReportService.ReportInterface)(this)).validateReportJob(inValue);
            operations = retVal.operations;
            units = retVal.units;
            requestId = retVal.requestId;
            return retVal.responseTime;
        }
    }
}
